server:
  port: 8301
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: eureka1
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2:8302/eureka

